### ISSUE TITLE
RedisToGo is getting shutdown

### ISSUE THREAD

**Issue by thienbao12a2** [Dhaiwat10/rlp-proxy#17]
They are shutting down RedisToGo in August. Do you have any other redis service that you could recommend?

**Comment by Dhaiwat10** [comment]
I have no clue unfortunately. :(

**Comment by thienbao12a2** [comment]
> I have no clue unfortunately. :(
That's fine. Could you please explain why we have to use Redis and Supabase? I entered a dummy Supabase anon key, and the server still works

**Comment by Dhaiwat10** [comment]
@thienbao12a2 it's just to cache results so the next time there is a request for the same URL, the server just grabs the cached result insetead of going and fetching data again. It's faster

**Comment by thienbao12a2** [comment]
> @thienbao12a2 it's just to cache results so the next time there is a request for the same URL, the server just grabs the cached result insetead of going and fetching data again. It's faster

Thank you.
