### ISSUE TITLE
Not able to generate preview for below mentioned link

### ISSUE THREAD

**Issue by Logan1x** [Dhaiwat10/rlp-proxy#7]
Hey @Dhaiwat10, I am not able to generate a preview for https://monkeytype.com/ this link. I just wanted to figure out what is wrong with this link.

**Comment by Dhaiwat10** [comment]
@Logan1x thanks to #8, this should be working fine now. Let me know if it's fixed!

**Comment by Logan1x** [comment]
it's looking like this now. ( focus on starting two links)

![image](https://user-images.githubusercontent.com/10944610/134867523-f3e9c93b-54e6-4b34-9ea8-3585e5144c1f.png)

**Comment by Dhaiwat10** [comment]
This must be because the proxy gets & returns [https://monkeytype.com/mtsocial.png](https://monkeytype.com/mtsocial.png) as the `image` which is not _really_ an image :D

**Comment by Logan1x** [comment]
SO we cant do anything in this case, I guess right?

**Comment by Dhaiwat10** [comment]
> SO we cant do anything in this case, I guess right?

I'm afraid that's correct, yes

**Comment by Logan1x** [comment]
Thanks for the help :)
